# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestCase01PE16():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testCase01PE16(self):
    time.sleep(2)
    self.driver.get("http://127.0.0.1:5000/")
    time.sleep(2)
    self.driver.set_window_size(968, 1038)
    time.sleep(2)
   #self.driver.find_element(By.LINK_TEXT, "Sign Out").click()
   #time.sleep(3)
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "Register here").click()
    time.sleep(1)
    self.driver.find_element(By.NAME, "email").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "form").click()
    time.sleep(1)
    self.driver.find_element(By.NAME, "email").click()
    time.sleep(1)
    self.driver.find_element(By.NAME, "email").send_keys("juan23@gmail.eu")
    time.sleep(1)
    self.driver.find_element(By.ID, "password").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "password").send_keys("Texas55!")
    time.sleep(2)
    self.driver.find_element(By.ID, "cpassword").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "cpassword").send_keys("Texas55!")
    time.sleep(1)
    self.driver.find_element(By.NAME, "firstName").click()
    time.sleep(1)
    self.driver.find_element(By.NAME, "firstName").send_keys("Juan")
    time.sleep(1)
    self.driver.find_element(By.NAME, "lastName").click()
    time.sleep(1)
    self.driver.find_element(By.NAME, "lastName").send_keys("Carlos")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "form").click()
    time.sleep(1)
    self.driver.find_element(By.NAME, "address1").click()
    time.sleep(1)
    self.driver.find_element(By.NAME, "address1").click()
    time.sleep(1)
    self.driver.find_element(By.NAME, "address1").send_keys("Forest Lane")
    time.sleep(1)
    self.driver.find_element(By.NAME, "address2").click()
    time.sleep(1)
    self.driver.find_element(By.NAME, "address2").send_keys("Audelia Road")
    time.sleep(2)
    self.driver.find_element(By.NAME, "zipcode").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "zipcode").send_keys("78201")
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "form").click()
    time.sleep(1)
    self.driver.find_element(By.NAME, "city").click()
    time.sleep(1)
    self.driver.find_element(By.NAME, "city").send_keys("San Antonio")
    time.sleep(1)
    self.driver.find_element(By.NAME, "state").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "state").send_keys("Texas")
    time.sleep(1)
    self.driver.find_element(By.NAME, "country").click()
    time.sleep(1)
    self.driver.find_element(By.NAME, "country").send_keys("United States")
    time.sleep(1)
    self.driver.find_element(By.NAME, "phone").click()
    time.sleep(2)
    self.driver.find_element(By.NAME, "phone").send_keys("737 654 234")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(13) > input").click()
    time.sleep(1)
    self.driver.find_element(By.NAME, "email").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    time.sleep(1)
    self.driver.find_element(By.NAME, "email").click()
  
